#!/usr/bin/env python3
"""Render pinned, secret-free CI caller workflows from the repo manifest."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "governance" / "repositories.json"


def render_caller(repo: dict[str, str], workflow_ref: str) -> str:
    branch = repo["default_branch"]
    return f"""# Generated by Elusor8/.github/scripts/render_callers.py. Do not hand-edit.
name: CI

on:
  pull_request:
    branches: [{branch}]
  push:
    branches: [{branch}]

permissions:
  contents: read

concurrency:
  group: ci-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  verify:
    permissions:
      contents: read
    uses: Elusor8/.github/.github/workflows/ci-reusable.yml@{workflow_ref}
    with:
      profile: {repo['profile']}
      runtime-version: '{repo['runtime_version']}'
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workflow-ref", required=True)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()
    if re.fullmatch(r"[0-9a-fA-F]{40}", args.workflow_ref) is None:
        parser.error("--workflow-ref must be a full 40-character commit SHA")

    data = json.loads(args.manifest.read_text())
    for repo in data["repositories"]:
        destination = (
            args.output_dir / repo["name"] / ".github" / "workflows" / "ci.yml"
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render_caller(repo, args.workflow_ref))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
